// Custom tests. Not generated by Stainless.
package local

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"testing"
)

type roundTripperFunc func(*http.Request) (*http.Response, error)

func (f roundTripperFunc) RoundTrip(req *http.Request) (*http.Response, error) {
	return f(req)
}

func withTempHome(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	t.Setenv("HOME", root)
	t.Setenv("XDG_CACHE_HOME", "")
	t.Setenv("LOCALAPPDATA", "")
	return root
}

func setDefaultTransport(t *testing.T, rt http.RoundTripper) {
	t.Helper()
	orig := http.DefaultTransport
	http.DefaultTransport = rt
	t.Cleanup(func() {
		http.DefaultTransport = orig
	})
}

func expectedCachePath(t *testing.T) (string, string) {
	t.Helper()
	root, err := cacheDir()
	if err != nil {
		t.Fatalf("cacheDir failed: %v", err)
	}
	filename := binaryFilename()
	return root, filepath.Join(root, filename)
}

func TestResolveBinaryPath_UsesCacheWithoutNetwork(t *testing.T) {
	withTempHome(t)
	root, path := expectedCachePath(t)
	if err := os.MkdirAll(root, 0o755); err != nil {
		t.Fatalf("mkdir cache: %v", err)
	}
	if err := os.WriteFile(path, []byte("cached"), 0o755); err != nil {
		t.Fatalf("write cache: %v", err)
	}

	setDefaultTransport(t, roundTripperFunc(func(req *http.Request) (*http.Response, error) {
		t.Fatalf("unexpected network call to %s", req.URL.String())
		return nil, nil
	}))

	got, err := ResolveBinaryPath()
	if err != nil {
		t.Fatalf("ResolveBinaryPath error: %v", err)
	}
	if got != path {
		t.Fatalf("expected %s, got %s", path, got)
	}
}

func TestResolveBinaryPath_DownloadsWithPinnedVersion(t *testing.T) {
	withTempHome(t)
	t.Setenv("STAGEHAND_SERVER_VERSION", "stagehand-server/v0.0.1")

	root, path := expectedCachePath(t)
	filename := binaryFilename()

	setDefaultTransport(t, roundTripperFunc(func(req *http.Request) (*http.Response, error) {
		if strings.Contains(req.URL.Host, "api.github.com") {
			t.Fatalf("unexpected tag resolution call: %s", req.URL.String())
		}
		want := "https://github.com/browserbase/stagehand/releases/download/stagehand-server/v0.0.1/" + filename
		if req.URL.String() != want {
			t.Fatalf("unexpected download url: %s", req.URL.String())
		}
		body := io.NopCloser(bytes.NewBufferString("binary"))
		return &http.Response{StatusCode: http.StatusOK, Body: body}, nil
	}))

	got, err := ResolveBinaryPath()
	if err != nil {
		t.Fatalf("ResolveBinaryPath error: %v", err)
	}
	if got != path {
		t.Fatalf("expected %s, got %s", path, got)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read cache: %v", err)
	}
	if string(data) != "binary" {
		t.Fatalf("unexpected cache contents: %q", string(data))
	}
	if runtime.GOOS != "windows" {
		info, err := os.Stat(path)
		if err != nil {
			t.Fatalf("stat cache: %v", err)
		}
		if info.Mode()&0o100 == 0 {
			t.Fatalf("expected executable bit set")
		}
	}

	// ensure cache dir exists
	if _, err := os.Stat(root); err != nil {
		t.Fatalf("cache dir missing: %v", err)
	}
}

func TestResolveBinaryPath_ResolvesLatestTag(t *testing.T) {
	withTempHome(t)
	filename := binaryFilename()

	var callsMu sync.Mutex
	calls := []string{}

	setDefaultTransport(t, roundTripperFunc(func(req *http.Request) (*http.Response, error) {
		callsMu.Lock()
		calls = append(calls, req.URL.String())
		callsMu.Unlock()

		switch {
		case strings.Contains(req.URL.Host, "api.github.com"):
			payload := []map[string]string{{"tag_name": "stagehand-server/v9.9.9"}}
			buf, _ := json.Marshal(payload)
			return &http.Response{StatusCode: http.StatusOK, Body: io.NopCloser(bytes.NewBuffer(buf))}, nil
		case strings.Contains(req.URL.Host, "github.com"):
			want := "https://github.com/browserbase/stagehand/releases/download/stagehand-server/v9.9.9/" + filename
			if req.URL.String() != want {
				t.Fatalf("unexpected download url: %s", req.URL.String())
			}
			return &http.Response{StatusCode: http.StatusOK, Body: io.NopCloser(bytes.NewBufferString("binary"))}, nil
		default:
			t.Fatalf("unexpected host: %s", req.URL.Host)
		}
		return nil, nil
	}))

	_, err := ResolveBinaryPath()
	if err != nil {
		t.Fatalf("ResolveBinaryPath error: %v", err)
	}

	callsMu.Lock()
	defer callsMu.Unlock()
	if len(calls) < 2 {
		t.Fatalf("expected at least 2 calls, got %d", len(calls))
	}
}
