//go:build !windows

// Custom code. Not generated by Stainless.

package local

import (
	"os/exec"
	"syscall"
)

func processRunning(cmd *exec.Cmd) bool {
	if cmd == nil || cmd.Process == nil {
		return false
	}

	// Signal 0 checks if the process exists.
	err := cmd.Process.Signal(syscall.Signal(0))
	return err == nil
}
