// Custom code. Not generated by Stainless.
package option

import (
	"fmt"
	"strings"

	"github.com/browserbase/stagehand-go/v3/internal/requestconfig"
)

// ServerOption represents a server mode selection for the client.
type ServerOption interface {
	Server() string
}

type serverOption struct {
	server string
}

func (o serverOption) Apply(*requestconfig.RequestConfig) error {
	return nil
}

func (o serverOption) Server() string {
	return o.server
}

// WithServer sets the server mode for the client.
// Valid values: "remote" (default), "local".
func WithServer(server string) RequestOption {
	mode := strings.ToLower(server)
	switch mode {
	case "remote", "local":
		return serverOption{server: mode}
	default:
		return requestconfig.RequestOptionFunc(func(*requestconfig.RequestConfig) error {
			return fmt.Errorf("option: invalid server %q", server)
		})
	}
}
